# Generated by Django 3.2.12 on 2022-05-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
    ]
